"""no_root

Revision ID: 2356d536d014
Revises: c7c44fd8d24e
Create Date: 2025-04-15 07:04:25.327036

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '2356d536d014'
down_revision = 'c7c44fd8d24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###