"""'resumes'

Revision ID: c7c44fd8d24e
Revises: 475998c5f82d
Create Date: 2025-04-11 18:58:06.313131

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7c44fd8d24e'
down_revision = '475998c5f82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('last_name', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('phone', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=True),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_competency'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes', schema='schema_competency')
    # ### end Alembic commands ###